[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shuiyuan-auto-reply"
version = "0.1.0"
description = "A project for automatic replies using LangChain and OpenRouter."
authors = [{ name = "Hydroiodic_Acid", email = "liao_chengfan@sjtu.edu.cn" }]
requires-python = ">=3.12"
dependencies = [
    "aiohttp",
    "apscheduler",
    "dacite",
    "dashscope",
    "ddgs",
    "httpx[socks]",
    "langchain-classic",
    "langchain-community",
    "langchain-openai",
    "langchain-mcp-adapters",
    "langgraph",
    "langgraph-checkpoint-postgres",
    "langmem",
    "neomodel",
    "numpy",
    "openai",
    "pandas",
    "pillow",
    "python-dotenv",
    "requests",
    "sentence-transformers",
    "skia-python",
    "sqlalchemy",
    "pytest>=9.0.3",
    "greenlet>=3.5.0",
]

[project.optional-dependencies]
dev = ["black", "isort"]
server = ["fastapi[all]"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
include = ["shuiyuan_auto_reply*"]

[tool.setuptools.package-data]
shuiyuan_auto_reply = [
    "assets/tarot_data.json",
    "assets/tarot_img/*.jpg",
    "assets/fonts/Noto_Color_Emoji/*.ttf",
    "assets/fonts/Noto_Color_Emoji/*.txt",
    "assets/fonts/Noto_Sans_SC/OFL.txt",
    "assets/fonts/Noto_Sans_SC/static/NotoSansSC-Bold.ttf",
    "assets/fonts/Noto_Sans_SC/static/NotoSansSC-Regular.ttf",
]

[tool.isort]
profile = "black"
