from typing import Any, Protocol


class ForumGateway(Protocol):
    async def get_post(self, post_id: int) -> Any: ...
    async def get_topic(self, topic_id: int) -> Any: ...
    async def get_actions(self, username: str, action_types: list[int]) -> Any: ...
    async def reply(
        self, text: str, topic_id: int, reply_to_post_number: int | None
    ) -> None: ...
